"""Generate a docker-compose.yml for any cluster topology.

The hand-written `docker/docker-compose.yml` is fixed at 3 nodes per service.
This script regenerates it for arbitrary counts, so you can deploy a 5-node
Raft lock cluster, a 7-node queue cluster, etc., without hand-editing YAML.

Usage:

    python tools/gen_compose.py --lock 5 --queue 4 --cache 3 \
        > docker/docker-compose.yml

Then:

    docker compose -f docker/docker-compose.yml --profile all up -d --build

Each service gets ID `<svc><i>` (e.g. `lock1`, `queue4`), bind 8001 inside the
container, and host port `1<svc_idx><i>` (lock=180xx, queue=181xx, cache=182xx)
so multiple clusters don't collide.

Notes:
* Raft tolerates `(n-1)/2` failures; odd counts (3, 5, 7) are recommended for
  the lock cluster.
* Queue replication factor is clamped to `min(--queue-rf, lock_count)`.
* All nodes within a service share the same `PEERS` env (full membership).
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass


HEADER = """# AUTO-GENERATED by tools/gen_compose.py — do not edit by hand.
# Regenerate with:  python tools/gen_compose.py --lock N --queue M --cache K
"""


@dataclass
class ServiceSpec:
    name: str          # 'lock' | 'queue' | 'cache'
    component: str     # python module under src.nodes
    profiles: list[str]
    count: int
    base_host_port: int  # 18010 for lock => 18011, 18012, ...
    extra_env: dict[str, str]


def _peers(spec: ServiceSpec) -> str:
    return ",".join(f"{spec.name}{i}@{spec.name}{i}:8001" for i in range(1, spec.count + 1))


def _service_block(spec: ServiceSpec, i: int, peers: str) -> str:
    name = f"{spec.name}{i}"
    host_port = spec.base_host_port + i
    env_lines = [
        f"      COMPONENT: {spec.component}",
        f"      NODE_ID: {name}",
        f"      NODE_BIND: 0.0.0.0:8001",
        f'      NODE_PORT: "8001"',
        f'      PEERS: "{peers}"',
        f"      DATA_DIR: /var/lib/dsync",
        f"      LOG_LEVEL: INFO",
    ]
    for k, v in spec.extra_env.items():
        env_lines.append(f'      {k}: "{v}"')
    profiles_line = "[" + ", ".join(spec.profiles) + "]"
    return (
        f"  {name}:\n"
        f"    <<: *node-base\n"
        f"    profiles: {profiles_line}\n"
        f"    container_name: {name}\n"
        f"    environment:\n" + "\n".join(env_lines) + "\n"
        f'    ports: ["{host_port}:8001"]\n'
        f'    volumes: ["{name}-data:/var/lib/dsync"]\n'
    )


def generate(lock: int, queue: int, cache: int, queue_rf: int,
             queue_vnodes: int, cache_capacity: int, cache_policy: str,
             include_redis: bool) -> str:
    if lock < 1 or queue < 1 or cache < 1:
        raise ValueError("each service must have at least 1 node")
    queue_rf = max(1, min(queue_rf, queue))

    specs = [
        ServiceSpec("lock", "lock_manager", ["lock", "all"], lock, 18010, {}),
        ServiceSpec("queue", "queue_node", ["queue", "all"], queue, 18020, {
            "QUEUE_REPLICATION_FACTOR": str(queue_rf),
            "QUEUE_VIRTUAL_NODES": str(queue_vnodes),
        }),
        ServiceSpec("cache", "cache_node", ["cache", "all"], cache, 18030, {
            "CACHE_CAPACITY": str(cache_capacity),
            "CACHE_POLICY": cache_policy,
        }),
    ]

    out: list[str] = [HEADER]
    out.append(
        "x-node-base: &node-base\n"
        "  build:\n"
        "    context: ..\n"
        "    dockerfile: docker/Dockerfile.node\n"
        "  networks: [dsync]\n"
        "  restart: unless-stopped\n"
        "  env_file: ../.env.example\n\n"
    )
    out.append("services:\n")

    if include_redis:
        out.append(
            "  redis:\n"
            "    image: redis:7-alpine\n"
            "    networks: [dsync]\n"
            "    profiles: [lock, queue, cache, all]\n"
            "    restart: unless-stopped\n\n"
        )

    for spec in specs:
        peers = _peers(spec)
        out.append(f"  # ---------- {spec.name} cluster ({spec.count} nodes) ----------\n")
        for i in range(1, spec.count + 1):
            out.append(_service_block(spec, i, peers))
            out.append("\n")

    out.append("networks:\n  dsync:\n    driver: bridge\n\n")
    out.append("volumes:\n")
    for spec in specs:
        for i in range(1, spec.count + 1):
            out.append(f"  {spec.name}{i}-data: {{}}\n")

    return "".join(out)


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--lock", type=int, default=3)
    p.add_argument("--queue", type=int, default=3)
    p.add_argument("--cache", type=int, default=3)
    p.add_argument("--queue-rf", type=int, default=2, help="queue replication factor")
    p.add_argument("--queue-vnodes", type=int, default=128, help="virtual nodes per queue node")
    p.add_argument("--cache-capacity", type=int, default=1024)
    p.add_argument("--cache-policy", choices=["LRU", "LFU"], default="LRU")
    p.add_argument("--no-redis", action="store_true")
    p.add_argument("-o", "--output", default="-", help="output file (default: stdout)")
    args = p.parse_args()

    yaml = generate(
        lock=args.lock,
        queue=args.queue,
        cache=args.cache,
        queue_rf=args.queue_rf,
        queue_vnodes=args.queue_vnodes,
        cache_capacity=args.cache_capacity,
        cache_policy=args.cache_policy,
        include_redis=not args.no_redis,
    )

    if args.output == "-":
        sys.stdout.write(yaml)
    else:
        with open(args.output, "w", encoding="utf-8") as fh:
            fh.write(yaml)
        print(f"wrote {args.output}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
